BLL/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import render,HttpResponseRedirect
from django.http import HttpResponse
def index(request):
    return HttpResponse('123')
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url("^$", index),
    url(r"^asset/", include('asset.urls')),

]

asset/urls.py
from django.conf.urls import url
from . import views
app_name = 'asset'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$',views.AssetCreateView.as_view(),name='add'),
]

asset/models.py
# coding: utf-8

import datetime
from django.db import models
from user.models import User, UserGroup

ASSET_ENV = (
    (1, U'生产环境'),
    (2, U'测试环境'),
    (3, U'autoscaling')
    )

ASSET_STATUS = (
    (1, u"已使用"),
    (2, u"未使用"),
    (3, u"报废")
    )





class Asset(models.Model):
    """
    asset modle
    """
    ip = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"主机IP")
    private_ip = models.CharField(max_length=255, blank=True, null=True, verbose_name=u"other IP")
    hostname = models.CharField(unique=True, max_length=128, verbose_name=u"主机名")
    port = models.IntegerField(blank=True, null=True, verbose_name=u"端口号")
    username = models.CharField(max_length=16, blank=True, null=True, verbose_name=u"管理用户名")
    password = models.CharField(max_length=256, blank=True, null=True, verbose_name=u"密码")
    use_default_auth = models.BooleanField(default=True, verbose_name=u"使用默认管理账号")
    mac = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"MAC地址")
    cpu = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'CPU')
    memory = models.CharField(max_length=128, blank=True, null=True, verbose_name=u'内存')
    disk = models.CharField(max_length=1024, blank=True, null=True, verbose_name=u'硬盘')
    system_type = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"系统类型")
    system_version = models.CharField(max_length=8, blank=True, null=True, verbose_name=u"系统版本号")
    status = models.CharField(max_length=50, blank=True, null=True, default=1, verbose_name=u"机器状态")
    env = models.IntegerField(choices=ASSET_ENV, blank=True, null=True, verbose_name=u"运行环境")
    date_added = models.DateTimeField(auto_now=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name=u"是否激活")
    comment = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"备注")

    def __str__(self):
        return self.ip

user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
import time

class UserGroup(models.Model):

    name = models.CharField(max_length=80, unique=True)

    comment = models.CharField(max_length=160, blank=True, null=True)

    def __str_(self):
        return self.name


class User(AbstractUser):
    USER_ROLE_CHOICES = (
        ('SU', 'SuperUser'),
        ('GA', 'GroupAdmin'),
        ('CU', 'CommonUser'),
    )
    name = models.CharField(max_length=80)
    uuid = models.CharField(max_length=100)
    role = models.CharField(max_length=2, choices=USER_ROLE_CHOICES, default='CU')
    group = models.ManyToManyField(UserGroup)


    def __str__(self):
        return self.username


class AdminGroup(models.Model):
    """
    under the user control group
    用户可以管理的用户组，或组的管理员是该用户
    """

    user = models.ForeignKey(User)
    group = models.ForeignKey(UserGroup)

    def __str__(self):
        return '%s: %s' % (self.user.username, self.group.name)


# class Document(models.Model):
#     def upload_to(self, filename):
#         return 'upload/'+str(self.user.id)+time.strftime('/%Y/%m/%d/', time.localtime())+filename
#
#     docfile = models.FileField(upload_to=upload_to)
#     user = models.ForeignKey(User)

asset/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from .models import Asset
# Create your views here.
class IndexView(ListView):
    model = Asset
    template_name = 'asset/index.html'
    context_object_name = 'asset_list'
    fields = ['ip', 'hostname','env','cpu','memory','disk']



class AssetCreateView(CreateView):
    model =Asset
    template_name= 'asset/add.html'
    fields = ['hostname','ip','port','username','password','use_default_auth','is_active']

user/views.py
from django.shortcuts import render

# Create your views here.

templates/asset/add.html
{% extends 'base.html' %}
{% load bootstrap %}
 {% block main %}
<form action="" method="post">
    {% csrf_token %}

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
		  <div class="header">
                        <h1 class="page-header">
                            <small>添加资产</small>
                        </h1>
						<ol class="breadcrumb">
					  <li><a href="{% url 'asset:index' %}">仪表盘</a></li>
					  <li><a href="#">Forms</a></li>
					  <li class="active">Data</li>
					</ol>

		</div>

            <div id="page-inner">
                       <div class="row">
                        <div class="col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="card-title">
                                        <div class="title">添加资产</div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    填写资产基本信息
                                    <div class="sub-title">{{ form|bootstrap_horizontal}}</div>
 <button class="ui button" type="submit">添加</button>
 </form>
{% endblock main %}

templates/asset/asset_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    <h1>delete it</h1>
    {% csrf_token%}

    <button class="ui button" type="submit">确认</button>
</form>
</body>
</html>

templates/asset/asset_update_form.html
{% extends 'base.html' %}
{% load bootstrap %}
 {% block main %}
<form action="" method="post">
    {% csrf_token %}

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
		  <div class="header">
                        <h1 class="page-header">
                            <small>更新资产</small>
                        </h1>
						<ol class="breadcrumb">
					  <li><a href="#">仪表盘</a></li>
					  <li><a href="#">Forms</a></li>
					  <li class="active">Data</li>
					</ol>

		</div>

            <div id="page-inner">
                       <div class="row">
                        <div class="col-xs-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <div class="card-title">
                                        <div class="title">更新资产</div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    填写项目基本信息
                                    <div class="sub-title">{{ form|bootstrap}}</div>
 <button class="ui button" type="submit">更新</button>
 </form>
{% endblock main %}

templates/asset/index.html
{% extends 'base.html' %}

 {% block main %}

     <div id="page-wrapper" >
		  <div class="header">
                        <h1 class="page-header">
                            资产列表
                        </h1>
						<ol class="breadcrumb">
					  <li><a href="#">Home</a></li>
					  <li><a href="#">Tables</a></li>
					  <li class="active">Data</li>
					</ol>
		</div>

            <div id="page-inner">

            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">

                             <a href="{% url 'asset:add'  %}" class="btn btn-info"> 添加资产</a>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>

                                        <tr>
                                            <th>主机名</th>
                                            <th>ip</th>

                                            <th>操作系统</th>
                                            <th>cpu</th>
                                            <th>内存</th>
                                            <th>硬盘</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       {% for asset in asset_list %}
                                        <tr class="odd gradeX">
                                            <td>{{ asset.hostname }}</td>
                                            <td>{{ asset.ip }}</td>
                                            <td class="center">{{ asset.env }}</td>
                                            <td class="center">{{ asset.cpu }}</td>
                                            <td class="center">{{ asset.memory }}</td>
                                            <td class="center">{{ asset.disk }}</td>
                                        </tr>
                                        {% empty %}
                                         {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                    <!--End Advanced Tables -->
                </div>
            </div>
  {% endblock main %}